### PR TITLE
FC-0001: Account pages -> micro-frontend

### PR DESCRIPTION
**Pull request by UvgenGen**
**Description:**

Added ACCOUNT_PROFILE_URL and ACCOUNT_SETTINGS_URL settings.

edx-platform PR: https://github.com/openedx/edx-platform/pull/30336
frontend-platform PR: https://github.com/openedx/frontend-platform/pull/326

## Supporting information
https://github.com/openedx/public-engineering/issues/71
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-17

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UvgenGen! I've created [OSPR-6653](https://openedx.atlassian.net/browse/OSPR-6653) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@UvgenGen Could you look into the failing CI test?

**Comment by UvgenGen** [comment]
@natabene Linter error fixed.

**Comment by natabene** [comment]
@UvgenGen Let's see how tests turn out.

**Comment by natabene** [comment]
@arbrandes This is ready for your review.

**Review by arbrandes — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@UvgenGen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-component-header&entry.867055334=https://github.com/openedx/frontend-component-header/pull/210&entry.1484655318=https://github.com/UvgenGen&entry.752974735=2022-05-02+14:03&entry.1917517419=2022-12-02+12:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
