### PR TITLE
feat: configureable header links

### PR DESCRIPTION
**Pull request by asadali145**
## Issue
https://github.com/openedx/platform-roadmap/issues/349

## Description
Makes header links, labels, and User name display more customizable using the configurations.

## Testing

- You can test this PR with the [Account MFE](https://github.com/openedx/frontend-app-account/) & [Learning MFE](https://github.com/openedx/frontend-app-learning/)
- Set these variables in .env.development of the Account & Learning MFE
  - `SHOW_FULLNAME=true`
  - `DASHBOARD_URL=<ANY URL>`
  - `EXTERNAL_ACCOUNT_PROFILE_URL=<ANY URL>`
  - `SHOW_SETTINGS_LABEL=true`
  - `ACCOUNT_SETTINGS_URL=http://localhost:1997`
- Use the local version of this header component and checkout this branch
- For header, run:
  - npm i
  - npm run build
- Now start the MFEs
- Header should reflect the configured changes.
- Also, test without the variables and the defaults should match the master branch.

## Screenshots
Screenshot 2024-03-29 at 5 34 39 PM

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @asadali145! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mphilbrick211** [comment]
Hi @asadali145! Would you mind resolving the branch conflicts while I look for someone to review for you? Thanks!

**Comment by asadali145** [comment]
@arbrandes What are your thoughts on this PR? It is similar to the footer PR https://github.com/openedx/frontend-component-footer/pull/403 related to https://github.com/openedx/platform-roadmap/issues/324

**Comment by arbrandes** [comment]
@asadali145, the latest on this is that we'll be addressing header configurability as part of the OEP-65/Module Federation work.  For the most part, it will be done as proposed here:

https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4412243977/Proposal+Customizable+Header+for+LMS

In the meantime, we're also adding PluginSlots to the header, such as this one.

https://github.com/openedx/frontend-component-header/pull/528

The slots should be ready by Sumac.

**Comment by pdpinch** [comment]
@asadali145 should we pursue this via the header pluginslot instead of configuration settings?

**Comment by asadali145** [comment]
> @asadali145 should we pursue this via the header pluginslot instead of configuration settings?

@pdpinch I don't think there is much that I can do at the moment per [this comment ](https://github.com/openedx/frontend-component-footer/pull/403#issuecomment-2377618223)on my footer PR

**Comment by davidjoy** [comment]
My recommendation would be for us to add plugin slots to the header/footer to support customization use cases for now, I think @brian-smith-tcril is helping with this effort.  

As the comment @asadali145 linked mentions, we're working on a longer-term version of the header and footer which will support more customization through simple configuration.  That's taking some time to get right, and won't be available for a while.  Certainly not by Sumac, _maybe_ by Teak.

**Comment by asadali145** [comment]
Closing this one as we have header slots for most of the things. Thanks for the work making it happen.

**Pull request closed without merging**
