### PR TITLE
pt-br-translate

### PR DESCRIPTION
**Pull request by elisreginazoche**
Adding pt-br translations

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @elisreginazoche! Thank you for your contribution! In order to proceed, you'll need to fill out a CLA form as mentioned above. Please let us know if you have any questions.

**Comment by mphilbrick211** [comment]
Hi @elisreginazoche! The tests are now running on this PR. Please remember to submit your CLA form so we can get this reviewed for you. Thanks!

**Comment by mphilbrick211** [comment]
> Hi @elisreginazoche! The tests are now running on this PR. Please remember to submit your CLA form so we can get this reviewed for you. Thanks!

Hi @elisreginazoche! Just seeing if you are planning to pursue this PR? If so, please submit your CLA form. If you're having trouble with the form--or have questions--please let me know. Thanks!

**Comment by mphilbrick211** [comment]
Hi @elisreginazoche! I'm going to close this PR for now. We can reopen it if you choose to pursue in the future. Thanks!

**Comment by openedx-webhooks** [comment]
@elisreginazoche Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-component-header&entry.867055334=https://github.com/openedx/frontend-component-header/pull/309&entry.1484655318=https://github.com/elisreginazoche&entry.752974735=2023-02-27+12:50&entry.1917517419=2023-05-10+20:22&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
